services:
  checkout:
    image: node:24-bookworm
    environment:
      HOST: 0.0.0.0
    ports:
      - "4000:4000"
      - "5173:5173"
    volumes:
      - .:/checkout
    working_dir: /checkout
    command: ["npm", "run", "dev"]
    restart: "no"
